# Generated by Django 4.2.29 on 2026-03-31 20:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3498db', help_text='Hex color code, e.g., #3498db', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('recurrence', recurrence.fields.RecurrenceField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancel_reason', models.TextField(blank=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('guests', models.JSONField(blank=True, default=list, help_text='Guest RSVPs: [{"name": "...", "status": "coming"}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='calendar_app.tag')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CalendarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ntfy_topic', models.CharField(blank=True, default='', help_text='ntfy.sh topic for push notifications', max_length=255)),
                ('language', models.CharField(blank=True, default='en', help_text='User language preference', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='calendar_app.tag')),
            ],
            options={
                'ordering': ['name', 'team'],
                'unique_together': {('name', 'team')},
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField(help_text='The specific date of the occurrence (for recurring events)')),
                ('status', models.CharField(choices=[('coming', 'Coming'), ('not_coming', 'Not Coming'), ('maybe', 'Maybe')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='calendar_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='calendar_app.calendaruser')),
            ],
            options={
                'ordering': ['status_updated_at'],
                'unique_together': {('event', 'occurrence_date', 'user')},
            },
        ),
        migrations.CreateModel(
            name='OccurrenceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_date', models.DateField(help_text='The specific date of this occurrence')),
                ('cancelled', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, help_text='Cancellation reason or general notice')),
                ('override_start_time', models.TimeField(blank=True, help_text='Override default start time (optional)', null=True)),
                ('override_end_time', models.TimeField(blank=True, help_text='Override default end time (optional)', null=True)),
                ('guests', models.JSONField(blank=True, default=list, help_text='Guest RSVPs for this occurrence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_details', to='calendar_app.event')),
            ],
            options={
                'verbose_name_plural': 'Occurrence details',
                'ordering': ['occurrence_date'],
                'unique_together': {('event', 'occurrence_date')},
            },
        ),
    ]
