# Generated by Django 4.2.29 on 2026-04-01 06:25

from django.db import migrations, models


def migrate_ntfy_settings(apps, schema_editor):
    CalendarUser = apps.get_model("calendar_app", "CalendarUser")
    for user in CalendarUser.objects.exclude(ntfy_topic=""):
        user.ntfy_enabled = True
        user.ntfy_server = "ntfy.sh"
        user.save(update_fields=["ntfy_enabled", "ntfy_server"])


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendaruser",
            name="ntfy_enabled",
            field=models.BooleanField(default=False, help_text="Enable push notifications via ntfy"),
        ),
        migrations.AddField(
            model_name="calendaruser",
            name="ntfy_server",
            field=models.CharField(blank=True, default="", help_text="ntfy server hostname (e.g., ntfy.sh)", max_length=255),
        ),
        migrations.RunPython(migrate_ntfy_settings, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="calendaruser",
            name="ntfy_topic",
        ),
    ]
