# Generated by Django 4.2.29 on 2026-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_calendaruser_rsvp_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.JSONField(blank=True, default=list, help_text='Guest RSVPs: [{"name": "...", "status": "coming"}]'),
        ),
        migrations.AddField(
            model_name='occurrencedetails',
            name='guests',
            field=models.JSONField(blank=True, default=list, help_text='Guest RSVPs for this occurrence'),
        ),
    ]
