# Generated by Django 4.2.29 on 2026-04-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_remove_calendaruser_ntfy_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaruser',
            name='theme',
            field=models.CharField(blank=True, default='', help_text='User theme preference (light/dark)', max_length=10),
        ),
    ]
