# Generated by Django 4.2.29 on 2026-08-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_calendaruser_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencedetails',
            name='override_description',
            field=models.TextField(blank=True, help_text='Override default description (optional)'),
        ),
        migrations.AddField(
            model_name='occurrencedetails',
            name='override_title',
            field=models.CharField(blank=True, help_text='Override default title (optional)', max_length=200),
        ),
    ]
